name: Sync to Bug_bounty_notes

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      B_TOKEN: ${{ secrets.B_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions-sync"
          git config user.email "sync-bot@example.com"

      - name: Add remote and push
        run: |
          git remote add b https://x-access-token:$B_TOKEN@github.com/Back0ntrack2/Bug_bounty_notes.git
          git push b main --force
