name: Sync to Bug_bounty_notes

on:
  push:
    branches: [ main ]   # change if your default branch is different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BugHuntingMadeEasy
        uses: actions/checkout@v3

      - name: Push to Bug_bounty_notes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add b https://x-access-token:${{ secrets.B_TOKEN }}@github.com/Back0ntrack2/Bug_bounty_notes.git
          git push b main --force
